language: rust
os:
  - linux

dist: xenial

rust:
  - stable

sudo: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ocl-dev/intel-opencl'
    packages:
      - intel-opencl
      - ocl-icd-opencl-dev

matrix:
  include:
    - os: linux
      script:
        - cargo build --verbose
        - cargo doc

    - os: linux
      rust: stable
      name: clippy
      install:
        - rustup component add clippy
      script:
        - cargo clippy --verbose -- -W clippy::derive_ord_xor_partial_ord -W clippy::if_same_then_else -W clippy::inherent_to_string_shadow_display
